### ISSUE TITLE
Some doubts about parameters used

### ISSUE THREAD

**Issue by ktiwari9** [EnstaBretagneClubRobo/enstaB-ros#1]
Hi there,
I want to use your astar node to use my occupancy grid and generate a path from start to the goal position. I am  not sure what you mean by  
map_frame_ = "/map_star";
base_frame_ = "/base_star";
My occupancy grid is being advertised on the topic called /local_grid and my rviz fixed frame is set to /odom so what should the values of map_frame and base_frame for my case ?

**Comment by Elessog** [comment]
Hello,
The map frame should be the frame id of the map and base frame is the frame of the robot.
If you want to test just use a static tf broadcaster between those two frame, then use goal service to 
create yours, but be aware that this package has not been debug and the tf listener is maybe inverted (line 88 in cpp file).
